/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexImport } from './routes/_authenticated/index'
import { Route as AuthenticatedMyOrdersIndexImport } from './routes/_authenticated/my-orders/index'
import { Route as AuthenticatedMenuDishesImport } from './routes/_authenticated/menu/dishes'
import { Route as AuthenticatedMenuCategoriesImport } from './routes/_authenticated/menu/categories'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedIndexRoute = AuthenticatedIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedMyOrdersIndexRoute = AuthenticatedMyOrdersIndexImport.update(
  {
    id: '/my-orders/',
    path: '/my-orders/',
    getParentRoute: () => AuthenticatedRoute,
  } as any,
)

const AuthenticatedMenuDishesRoute = AuthenticatedMenuDishesImport.update({
  id: '/menu/dishes',
  path: '/menu/dishes',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedMenuCategoriesRoute =
  AuthenticatedMenuCategoriesImport.update({
    id: '/menu/categories',
    path: '/menu/categories',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/menu/categories': {
      id: '/_authenticated/menu/categories'
      path: '/menu/categories'
      fullPath: '/menu/categories'
      preLoaderRoute: typeof AuthenticatedMenuCategoriesImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/menu/dishes': {
      id: '/_authenticated/menu/dishes'
      path: '/menu/dishes'
      fullPath: '/menu/dishes'
      preLoaderRoute: typeof AuthenticatedMenuDishesImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/my-orders/': {
      id: '/_authenticated/my-orders/'
      path: '/my-orders'
      fullPath: '/my-orders'
      preLoaderRoute: typeof AuthenticatedMyOrdersIndexImport
      parentRoute: typeof AuthenticatedImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedMenuCategoriesRoute: typeof AuthenticatedMenuCategoriesRoute
  AuthenticatedMenuDishesRoute: typeof AuthenticatedMenuDishesRoute
  AuthenticatedMyOrdersIndexRoute: typeof AuthenticatedMyOrdersIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedMenuCategoriesRoute: AuthenticatedMenuCategoriesRoute,
  AuthenticatedMenuDishesRoute: AuthenticatedMenuDishesRoute,
  AuthenticatedMyOrdersIndexRoute: AuthenticatedMyOrdersIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/menu/categories': typeof AuthenticatedMenuCategoriesRoute
  '/menu/dishes': typeof AuthenticatedMenuDishesRoute
  '/my-orders': typeof AuthenticatedMyOrdersIndexRoute
}

export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/menu/categories': typeof AuthenticatedMenuCategoriesRoute
  '/menu/dishes': typeof AuthenticatedMenuDishesRoute
  '/my-orders': typeof AuthenticatedMyOrdersIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/menu/categories': typeof AuthenticatedMenuCategoriesRoute
  '/_authenticated/menu/dishes': typeof AuthenticatedMenuDishesRoute
  '/_authenticated/my-orders/': typeof AuthenticatedMyOrdersIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/login'
    | '/'
    | '/menu/categories'
    | '/menu/dishes'
    | '/my-orders'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/' | '/menu/categories' | '/menu/dishes' | '/my-orders'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/'
    | '/_authenticated/menu/categories'
    | '/_authenticated/menu/dishes'
    | '/_authenticated/my-orders/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated",
        "/login"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/",
        "/_authenticated/menu/categories",
        "/_authenticated/menu/dishes",
        "/_authenticated/my-orders/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_authenticated/": {
      "filePath": "_authenticated/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/menu/categories": {
      "filePath": "_authenticated/menu/categories.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/menu/dishes": {
      "filePath": "_authenticated/menu/dishes.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/my-orders/": {
      "filePath": "_authenticated/my-orders/index.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
